### ISSUE TITLE
[FEATURE REQUEST] - Is it possible to support multi word token feature for search?

### ISSUE THREAD

**Issue by sujit-baniya** [micpst/fts-engine#1]
Thank you for this library. I find it useful for my project. Please let me know if there's any way I could search by multi word. With this feature, it would first search by all words in query and return well filtered records.

For e.g.

```js
[
{"code": "O24113", "desc": "Pre-existing type 2 diabetes mellitus, in pregnancy, third trimester"}, {"code": "O24119", "desc": "Pre-existing type 2 diabetes mellitus, in pregnancy, unspecified trimester"}, {"code": "O2412", "desc": "Pre-existing type 2 diabetes mellitus, in childbirth"}, {"code": "O2413", "desc": "Pre-existing type 2 diabetes mellitus, in the puerperium"}, {"code": "O24311", "desc": "Unspecified pre-existing diabetes mellitus in pregnancy, first trimester"}, {"code": "O24312", "desc": "Unspecified pre-existing diabetes mellitus in pregnancy, second trimester"}, {"code": "O24313", "desc": "Unspecified pre-existing diabetes mellitus in pregnancy, third trimester"}, {"code": "O24319", "desc": "Unspecified pre-existing diabetes mellitus in pregnancy, unspecified trimester"}, {"code": "O2432", "desc": "Unspecified pre-existing diabetes mellitus in childbirth"}, {"code": "O2433", "desc": "Unspecified pre-existing diabetes mellitus in the puerperium"}, {"code": "O24410", "desc": "Gestational diabetes mellitus in pregnancy, diet controlled"}, {"code": "O24414", "desc": "Gestational diabetes mellitus in pregnancy, insulin controlled"}, {"code": "O24415", "desc": "Gestational diabetes mellitus in pregnancy, controlled by oral hypoglycemic drugs"}
]
```
In this example, when I search 
1) for `diabetes`, I would see all entries in result. 
2) for `Gestational diabetes`, it would return only records with matching query
3) for `diabetes in pregnancy`, it would return specific results only

**Comment by micpst** [comment]
Currently you can't search this way, but it should be fairly easy to implement. I will add an `exact` flag to parameterize the search.

**Comment by sujit-baniya** [comment]
@micpst Thanks for the response, I would not prefer `exact` flag since it would search all words as-is in the query.  I've used `intersect` for now to get the data as per required.

I think there's a problem with `InsertBatch`  specially on line
https://github.com/micpst/fts-engine/blob/master/src/store/store.go#L156

It's causing DATA RACE for large dataset, and the result is unexpected

**Comment by micpst** [comment]
According to your requirements you wanted to get only results with matching query, so the `exact` flag will do just that. Calculating intersection is just another word for that.

The error with `InsertBatch` you mentioned should be opened as another issue, but I think it is caused by the `cornelk/hashmap` library, which seems to have a bug.

**Comment by sujit-baniya** [comment]
Create another bug
https://github.com/micpst/fts-engine/issues/2

I've tried with both `sync.Map` and `map` resulting DATA RACE

**Comment by sujit-baniya** [comment]
> so the exact flag will do just that. Calculating intersection is just another word for that.
Yeah :)
