### ISSUE TITLE
[Bug] - Data race with InsertBatch

### ISSUE THREAD

**Issue by sujit-baniya** [micpst/fts-engine#2]
There's a problem with InsertBatch specially on line
https://github.com/micpst/fts-engine/blob/master/src/store/store.go#L156

It's causing DATA RACE for large dataset, and the result is unexpected.

I've tried with `sync.Map` or `map` both resulted with DATA RACE. Maybe logic requires re-thinking

**Comment by sujit-baniya** [comment]
@micpst The gist I've created out of this repo
https://gist.github.com/sujit-baniya/ec0457a2dfa3392d3005db357089d6ee

Data I've used:
https://gist.github.com/cryocaustik/b86de96e66489ada97c25fc25f755de0#file-icd10_codes-json

DATA RACE
![image](https://user-images.githubusercontent.com/4959215/210393106-25a48ca8-04a1-44a3-8f98-bf9ddb895718.png)

**Comment by micpst** [comment]
Ok, thank you, I will look into it.
