### ISSUE TITLE
[FEATURE REQUEST] - Allow support for other data types except struct

### ISSUE THREAD

**Issue by sujit-baniya** [micpst/fts-engine#4]
Currently `getIndexFields` is only considering struct. I think this library should also support other data types such as `map[string]any`, `string`, numbers or date time

```go
func getIndexFields(obj any) []string {
	fields := make([]string, 0)
	val := reflect.ValueOf(obj)
	t := reflect.TypeOf(obj)

	for i := 0; i < val.NumField(); i++ {
		f := t.Field(i)
		if v, ok := f.Tag.Lookup("index"); ok && v == "true" {
			fields = append(fields, val.Field(i).String())
		}
	}

	return fields
}
```

**Comment by micpst** [comment]
This function parses the fields of `Schema` struct to retrieve indexable properties and is intended for internal use by the `storage` package, there is no need to add more complexity to it.

If you want to store different data types you can do so by defining them in your schema.
